#!/bin/bash
set -uo pipefail

# The side-effect of the following line is to exit early if the vars are not set.
[[ -z "$DIR_TO_BACKUP" ]] || [[ -z "$BACKUP_BASE_DIR" ]]

if [ $(whoami) != "root" ]; then
    >&2 echo "This script must be run as root."
    exit 1
fi

bases=$(find "$BACKUP_BASE_DIR" -mindepth 1 -maxdepth 1 -type d -printf "%f %s " 2> /dev/null)

selected_base=$(whiptail \
    --title "Incremental backup" \
    --menu "Select the base (previous) backup to hardlink to" \
    14 40 6 \
    ${bases[@]} 3>&2 2>&1 1>&3-)
exit_code=$?

if [ ! $exit_code ] || [ "$selected_base" == "" ]; then
    >&2 echo "No selection."
    exit 1
fi

today=$(date '+%Y-%m-%d')

base="$BACKUP_BASE_DIR/$selected_base"
dest="$BACKUP_BASE_DIR/$today"
src="$DIR_TO_BACKUP/"

echo "Selected base backup to hardlink to: $base"
echo "New backup: $dest"
echo "Source: $src"

sleep 5

rsync -avv --delete --link-dest="$base" "$src" "$dest"
